version: '3'
services:
  downlink_service:
    build:
      context: .
    image: quay.io/team-helium/downlink_service:local
    container_name: downlink_service
    restart: unless-stopped
    ports:
      - 8180:80
      - 8280:8080
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=8080