version: '3'
services:
  downlink_service:
    build:
      context: .
    image: quay.io/team-helium/downlink_service:local
    container_name: downlink_service
    restart: unless-stopped
    ports:
      - 80:80
      - 50051:50051
      - 9000:9000